Fix Example Code
The current Example produces an compiler error due to double `;`


```
error: unreachable statement
    return firstName + " " + lastName;;
                                      ^
```